### ISSUE TITLE
`out` statement

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/DSL#1259]
### Is your feature request related to a problem?

In order to get the output of the operations, users must use code lenses. These are only shown for placeholders, depending on their type. 

Because of this, users must create many placeholders in their program that are solely used for output, but never referenced. Still, each placeholder must have a unique name, which either means that users spend time thinking of a proper name, or just quickly give them some garbage name.

### Desired solution

Add a new statement

`out <expression>`,

that is essentially an expression statement that shows code lenses. Determine the names shown in the code lenses based on the results of the function, if `<expression>` is a call. Otherwise, just call it "expression".

Keep the current behavior of

* disabling the unused placeholder warning if its name is prefixed by `_`,
* showing code lenses for placeholders based on their type.

### Possible alternatives (optional)

* Show code lenses for any expression statement: This would mean that we could no longer show a warning that an expression statement does nothing, which often indicates a bug. It's preferable that users explicitly assign the result or indicate that it is only for output.

### Additional Context (optional)

`out` is already a keyword in the language (covariance), so this PR is a non-breaking change.

**Tasks:**

- [x] Update grammar
- [x] Update VS Code syntaxes
- [x] Update formatter
- [x] Update slicer
- [x] Update code generator (must autogenerate placeholder names)
- [x] Update code lens provider
- [x] Update commands (show, explore, print)
- [x] Adjust warning that expression statement does nothing. "Did you forget assignment/out..."
- [x] Don't warn that output statement does nothing.
- [x] Error: Expression produces no results
- [x] Error: `out` is only allowed in pipeline
- [ ] Code added by EDA must replace the output statement by an assignment, so references are resolved (currently the EDA view is broken if triggered on an output statement)
- [ ] Update documentation
