### ISSUE TITLE
Behavior protocols in classes

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/DSL#19]
**Is your feature request related to a problem? Please describe.**
Not all chains of functions calls and attribute accesses are valid.

**Describe the solution you'd like**
* Specify behavior protocols
* Repetition (0-n or 1-n)
* Option
* Alternative
* Sequence
* Syntax: `protocol { f* g+ h? (i|j) k }` - here `f` to `k` are references to callables and attributes (meaning reading accesses)
* Can refer to instance methods and instance attributes the next surrounding class (cannot access anything in outer classes if nested)
* Only makes sense in classes since it describes the lifecycle of a single instance
* At most 1 per class
* ~~Must only be used in stub files~~ (that's a given if it can only be used in classes)

#### Semantics

* If a class has a protocol only call sequences that conform exactly to the protocol are allowed. There must be no unmatched call prefix or suffix and nothing unmatched in-between.
* Protocol can be overridden by subclasses. However, the overriding protocol must conform to the overridden protocol. A class can only specify additionally, when its own methods/attributes can be used.
* If a class `Sub` has no own protocol, but a superclass `Super` has, instances of `Sub` must adhere to the protocol defined in `Super`, when using features of `Super`. Methods defined in `Sub`, however, can be used freely.
* If a class has no own protocol and neither of its superclasses does, all features can be mixed freely.

### Tasks

- [x] Scoping (can point to subterms and functions/attributes defined in the class or inherited from a superclass)
- [x] Validation: referenced functions and attributes must not be static
- [x] Validation: no duplicate names for subterms
- [x] Update Prolog converter
- [x] Creators
- [x] Accessors
- [ ] Actual validation that calls conform to the protocol

**Comment by lars-reimann** [comment]
We won't work on this further until we find more use-cases. The feature is not worth pursuing just to ensure the `fit` is called before `predict` or `transform`. See also https://github.com/Safe-DS/DSL/pull/518.
