### ISSUE TITLE
Finalize & document the grammar

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/DSL#20]
### Tasks

- [X] lars-reimann/safe-data-science#19
- [ ] lars-reimann/safe-data-science#18
- [ ] Link to Xtext grammar file
- [ ] Describe how to read the grammar

**Comment by lars-reimann** [comment]
Closed in favor of individual issues.
