### ISSUE TITLE
Finalize & document the EMF model

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/DSL#21]
### Tasks

- [ ] lars-reimann/safe-data-science#37
- [x] lars-reimann/safe-data-science#28
- [ ] lars-reimann/safe-data-science#19
- [ ] lars-reimann/safe-data-science#18
- [x] lars-reimann/Simple-ML#100

**Comment by lars-reimann** [comment]
Closed in favor of individual issues.
