### ISSUE TITLE
Task: Generics (part 1)

### ISSUE THREAD

**Issue by AdrianBajraktari** [Safe-DS/DSL#23]
## Tasks

- [x] Compute type parameters for `NamedType`
- [x] Compute type parameters for `List`
- [x] Compute type parameters for `Map`
- [x] Update type computation for `IndexedAccess`
- [x] Update type checking for index of indexed access on map
- [x] Add new type "TypeParameterType"
- [x] Add methods `substituteTypeParameters(substitutions: TypeParameterSubstitutions)` to all types
- [x] `classTypeIsAssignableTo` must handle type parameters (+variance)
- [x] `ClassType.equals` needs to check type parameter substitutions
- [x] `ClassType.toString` should show type parameter substitutions
- [x] Type arguments & type parameters should no longer be experimental.
- [x] `IndexedAccess` should no longer be experimental

**Comment by lars-reimann** [comment]
I've moved the remaining tasks into separate issues due to their size.
